name: "Bug Report"
description: "File a bug report."
title: "[Bug]: "
labels: ["Bug", "Triage"]
projects: ["distributeaid/15"]
type: bug
body:
  - type: textarea
    id: who-are-you
    attributes:
      label: "Who are you?"
      description: "Give us enough information so that the developer working on this can reach out and ask you followup questions. Let folks know explicitly if you're a DA volunteer, coordinator, etc."
    validations:
      required: true

  - type: dropdown
    id: bug-type
    attributes:
      label: "Is the bug visual or functionality?"
      multiple: true
      options:
        - Visual
        - Funcionality
        - Missing Content
        - Other (Tell us more in the fields below)

  - type: textarea
    id: what-happened
    attributes:
      label: "What actually happens?"
      description: "Please provide step-by-step details if possible."
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: "What are you expecting to happen?"
      description: "A concise description of what you expected to happen."
    validations:
      required: true
  
  - type: textarea
    id: workarounds
    attributes:
      label: "What current workarounds are you using? Or are you stuck?"
    validations:
      required: true

  - type: dropdown
    id: affected-component
    attributes:
      label: "What area does the bug apply to?"
      multiple: true
      options:
        - APIs
        - Data models
        - Strapi UI

  - type: textarea
    id: affected-component-details
    attributes:
      label: "What part of the area is affected?"
      description: "Attach a screenshot, or specify the starting point of the process and describe where the issue occurs. "
      validations:
        required: true
  
  - type: upload
    id: screenshots
    attributes:
      label: "Upload screenshots"
      description: "If applicable, add any additional images or screenshots to help explain the problem you encountered."
    validation:
      required: false
  
  - type: textarea
    id: inspiration
    attributes:
      label: "Is there inspiration for how this should work?"
      description: "List links or screenshots of examples which demonstrate the fix you're requesting."
    validation:
      required: false